##Steps are same as that of Liga Primeira

In [1]:
import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df1=pd.read_csv(io.BytesIO(uploaded['Outfielders_Eredivisie_2023.csv']))

Saving Outfielders_Eredivisie_2023.csv to Outfielders_Eredivisie_2023.csv

In [2]:
pd.set_option('display.max_columns', 500)

In [5]:
#Only Run This Cell for Eredivisie
df1.loc[df1['Player'] == 'Givairo Read']

,Season,Squad,Comp,Player,Nation,Pos,Age,MP,Starts_Playing_Time,Min_Playing_Time,Mins_Per_90_Playing_Time,Gls,Ast,G+A,G_minus_PK,PK,PKatt,CrdY,CrdR,xG_Expected,npxG_Expected,xAG_Expected,npxG+xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per_Minutes,Ast_Per_Minutes,G+A_Per_Minutes,G_minus_PK_Per_Minutes,G+A_minus_PK_Per_Minutes,xG_Per_Minutes,xAG_Per_Minutes,xG+xAG_Per_Minutes,npxG_Per_Minutes,npxG+xAG_Per_Minutes,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Tkl_percent_Challenges,Lost_Challenges,Blocks_Blocks,Sh_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err,Cmp_Total,Att_Total,Cmp_percent_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_percent_Short,Cmp_Medium,Att_Medium,Cmp_percent_Medium,Cmp_Long,Att_Long,Cmp_percent_Long,xAG,xA,A_minus_xAG,KP,Final_Third,PPA,CrsPA,PrgP,Gls_Standard,Sh_Standard,SoT_Standard,SoT_percent_Standard,Sh_per_90_Standard,SoT_per_90_Standard,G_per_Sh_Standard,G_per_SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,npxG_per_Sh_Expected,G_minus_xG_Expected,np:G_minus_xG_Expected,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,SCA90_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,GCA90_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Succ_percent_Take_Ons,Tkld_Take_Ons,Tkld_percent_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,PrgC_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,PrgR_Receiving,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Won_percent_Aerial_Duels
371,2022-2023,Volendam,Eredivisie,Givairo Read,NaN,DF,17-000,1.0,0,6,0.1,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,2,0,1,2,50.0,13,0,1,1,100.0,0,1,0.0,0,0,NaN,0.0,0.0,0.0,0,0,0,0,0,0,0,0,NaN,0.0,0.0,NaN,NaN,NaN,0,0,0,NaN,0.0,0.0,2,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,4,1,2,2,0,0,4,0,0,NaN,0,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN

In [4]:
for i in range(len(df1)):
  if df1.loc[i, 'Player'] == 'Givairo Read':
    df1.loc[i, 'Age'] = '17-000'

In [6]:
for i in list(df1.columns):
  if 'percent' in i:
    print(i)

Tkl_percent_Challenges
Cmp_percent_Total
Cmp_percent_Short
Cmp_percent_Medium
Cmp_percent_Long
SoT_percent_Standard
Succ_percent_Take_Ons
Tkld_percent_Take_Ons
Won_percent_Aerial_Duels

##Drop Unnecessary Columns

In [7]:
#Drop Unnecessary Columns
df1.drop(columns = ['npxG_per_Sh_Expected', 'G_per_SoT_Standard', 'G_per_Sh_Standard', 'SoT_percent_Standard', 'Cmp_percent_Long', 'Cmp_percent_Medium', 'Cmp_percent_Short', 'Cmp_percent_Total', 'Tkl_percent_Challenges', 'G+A', 'npxG+xAG_Expected', 'G_minus_xG_Expected', 'G_minus_PK', 'CrdR', 'CrdY', 'A_minus_xAG', 'np:G_minus_xG_Expected', 'Blocks_Blocks', 'Tkl+Int', 'xAG', 'PrgP', 'Gls_Standard', 'Sh_per_90_Standard', 'SoT_per_90_Standard', 'SoT_percent_Standard', 'Succ_percent_Take_Ons', 'Tkld_percent_Take_Ons', 'Won_percent_Aerial_Duels'], inplace = True)

In [9]:
print(list(df1.columns))

['Season', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts_Playing_Time', 'Min_Playing_Time', 'Mins_Per_90_Playing_Time', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Gls_Per_Minutes', 'Ast_Per_Minutes', 'G+A_Per_Minutes', 'G_minus_PK_Per_Minutes', 'G+A_minus_PK_Per_Minutes', 'xG_Per_Minutes', 'xAG_Per_Minutes', 'xG+xAG_Per_Minutes', 'npxG_Per_Minutes', 'npxG+xAG_Per_Minutes', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'PK_Standard', 'PKatt_Standard', 'Att', 'Live_Pass_Types', 'Dead_Pass_Types', 'FK_Pass_Types', 'TB_Pass_Types', 'Sw_Pass_Types', 'Crs_Pass_Types', 'TI_Pass_Types', 'CK_Pass_Types', 'In_Corner_Kicks', 'Out_Corner_Kicks', 'Str_Corner_Kicks', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'SCA90_SCA', 'PassLive_SCA_Types', 'PassDead_SCA_Types', 'TO_SCA_Types', 'Sh_SCA_Types', 'Fld_SCA_Types', 'Def_SCA_Types', 'GCA_GCA', 'GCA90_GCA', 'PassLive_GCA_Types', 'PassDead_GCA_Types', 'TO_GCA_Types', 'Sh_GCA_Types', 'Fld_GCA_Types', 'Def_GCA_Types', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take_Ons', 'Succ_Take_Ons', 'Tkld_Take_Ons', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'PrgC_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'PrgR_Receiving', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial_Duels', 'Lost_Aerial_Duels']

In [10]:
df1.drop(columns = ['SCA90_SCA', 'GCA90_GCA', 'PrgC_Carries', 'PrgR_Receiving', '2CrdY', 'TklW'], inplace = True)

##Impute Missing Values with 0

In [11]:
#Impute all NaN values with 0
df1 = df1.fillna(0)

In [12]:
df1

,Season,Squad,Comp,Player,Nation,Pos,Age,MP,Starts_Playing_Time,Min_Playing_Time,Mins_Per_90_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per_Minutes,Ast_Per_Minutes,G+A_Per_Minutes,G_minus_PK_Per_Minutes,G+A_minus_PK_Per_Minutes,xG_Per_Minutes,xAG_Per_Minutes,xG+xAG_Per_Minutes,npxG_Per_Minutes,npxG+xAG_Per_Minutes,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels
0,2022-2023,Feyenoord,Eredivisie,Dávid Hancko,SVK,DF,25-177,31.0,31,2745,30.5,2,4,0,0,3.1,3.1,2.3,63,227,44,0.07,0.13,0.20,0.07,0.20,0.10,0.07,0.18,0.10,0.18,30.5,71,43,43,24,4,44,53,9,16,13,31,103,1,1986,2282,38119,13910,708,751,1056,1148,200,334,2.2,19,249,11,2,42,11,13.1,0,0,0,2282,2188,91,44,3,16,23,35,0,0,0,0,1986,3,13,65,52,2,2,6,3,0,6,3,0,0,3,0,0,2615,228,1015,1368,255,66,2615,19,13,5,1697,9450,6326,40,3,29,8,1818,12,19,2,23,0,0,0,231,37,24
1,2022-2023,Feyenoord,Eredivisie,Orkun Kökçü,TUR,MF,22-161,32.0,31,2696,30.0,8,2,2,2,5.6,4.1,7.1,91,379,104,0.27,0.07,0.33,0.20,0.27,0.19,0.24,0.42,0.14,0.37,30.0,39,18,12,15,12,17,45,28,6,10,19,16,0,2044,2510,36150,12660,920,1008,845,979,219,393,8.1,89,327,75,18,82,29,25.5,21,2,2,2510,2252,249,106,11,15,149,32,108,50,16,0,2044,9,39,196,131,43,7,11,4,0,15,9,1,2,2,1,0,2839,42,356,1598,918,53,2837,60,30,22,1822,9357,4726,77,10,58,44,2057,23,27,0,149,0,0,0,241,9,11
2,2022-2023,Feyenoord,Eredivisie,Lutsharel Geertruida,NED,"DF,MF",22-325,30.0,29,2572,28.6,3,2,0,0,3.2,3.2,2.4,64,211,48,0.10,0.07,0.17,0.10,0.17,0.11,0.08,0.20,0.11,0.20,28.6,48,34,24,21,3,21,28,7,6,6,31,48,1,1844,2043,32210,9930,746,802,948,1012,122,172,2.5,25,183,14,5,26,8,17.7,0,0,0,2043,1913,128,33,2,7,12,95,0,0,0,0,1844,2,16,66,60,2,1,1,2,0,7,6,0,1,0,0,0,2257,106,568,1380,321,33,2257,33,17,10,1516,8342,4900,40,5,22,15,1669,16,15,1,12,0,0,0,176,20,14
3,2022-2023,Feyenoord,Eredivisie,Marcus Pedersen,NOR,DF,22-327,29.0,25,2117,23.5,1,2,0,0,1.5,1.5,2.3,114,54,141,0.04,0.09,0.13,0.04,0.13,0.07,0.10,0.16,0.07,0.16,23.5,41,23,20,14,7,24,28,4,4,12,9,60,1,966,1177,15285,2783,497,546,392,463,57,105,2.7,30,61,22,14,19,4,17.5,0,0,0,1177,997,178,9,0,5,61,169,0,0,0,0,966,2,32,59,52,0,5,1,0,1,5,4,0,1,0,0,0,1407,76,331,627,464,66,1407,60,32,22,811,6081,3366,58,21,27,18,839,27,9,3,61,0,0,0,124,3,6
4,2022-2023,Feyenoord,Eredivisie,Sebastian Szymański,POL,"MF,FW",24-029,29.0,24,1966,21.8,9,4,0,0,6.0,6.0,4.1,39,91,142,0.41,0.18,0.60,0.41,0.60,0.27,0.19,0.46,0.27,0.46,21.8,51,29,13,26,12,24,47,23,2,26,11,11,1,582,829,9164,2961,310,363,179,249,61,128,5.4,50,48,36,11,59,23,19.4,4,0,0,829,704,121,15,4,7,115,5,87,42,19,0,582,4,33,107,62,32,4,3,3,3,12,9,1,0,1,1,0,1118,13,93,430,600,92,1118,49,14,31,613,2897,1414,32,9,47,27,704,25,33,1,115,0,0,0,96,7,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,2022-2023,Groningen,Eredivisie,Marin Šverko,CRO,DF,25-124,5.0,2,225,2.5,0,0,0,0,0.0,0.0,0.1,6,11,1,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.03,0.00,0.03,2.5,5,4,2,3,0,3,5,2,2,1,3,9,0,104,142,2169,664,36,43,53,68,15,29,0.0,2,8,0,0,0,0,0.0,0,0,0,142,118,24,3,1,1,0,18,0,0,0,0,104,0,2,3,3,0,0,0,0,0,0,0,0,0,0,0,0,170,23,75,90,8,0,170,4,3,1,86,675,487,4,0,2,2,85,5,1,0,0,0,0,0,14,6,3
483,2022-2023,Groningen,Eredivisie,Aimar Sher,SWE,"MF,FW",20-170,6.0,0,134,1.5,0,0,0,0,0.2,0.2,0.0,0,6,6,0.00,0.00,0.00,0.00,0.00,0.11,0.01,0.12,0.11,0.12,1.5,4,2,2,2,0,1,4,3,0,0,2,2,0,39,53,548,221,25,28,14,20,0,3,0.1,1,1,1,0,4,0,23.5,0,0,0,53,51,2,0,0,0,2,1,1,0,0,0,39,0,1,5,4,0,1,0,0,0,0,0,0,0,0,0,0,73,4,20,28,26,3,73,3,3,0,35,170,71,3,1,2,1,44,1,0,0,2,0,0,0,7,3,5
484,2022-2023,Groningen,Eredivisie,Yahya Kalley,SWE,"DF,MF",22-080,5.0,0,130,1.4,0,0,0,0,0.0,0.0,0.0,3,3,3,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.03,0.02,0.03,1.4,6,5,3,2,1,2,3,1,0,1,4,4,0,33,53,646,206,11,16,18,26,4,10,0.0,1,2,1,0,1,0,36.2,0,0,0,53,40,13,0,0,1,3,13,0,0,0,0,33,0,1,3,1,0,0,0,1,1,0,0,0,0,0,0,0,78,6,35,27,18,0,78,5,3,2,22,207,123,1,1,4,2,27,4,3,0,3,0,0,0,10,3,1
485,2022-2023,Groningen,Eredivisie,Romano Postema,NED,"MF,FW",21-121,2.0,0,35,0.4,0,0,0,0,0.1,0.1,0.1,0,2,4,0.00,0.00,0.00,0.00,0.00,0.26,0.14,0.40,0.26,0.40,0.4,2,1,1,1,0,2,2,0,0,1,0,0,0,9,9,160,54,5,5,3,3,1,1,0.0,1,1,0,0,1,1,11.3,0,0,0,9,8,1,0,0,0,0,0,0,0,0,0,9,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,18,0,1,10,7,2,18,0,0,0,12,38,19,0,0,2,1,12,0,1,0,0,0,0,0,2,1,0
486,2022-2023,Groningen,Eredivisie,Patrick Joosten,NED,FW,27-055,1.0,0,29,0.3,0,0,0,0,0.0,0.0,0.0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.3,0,0,0,0,0,0,0,0,0,0,1,0,0,3,3,37,16,2,2,1,1,0,0,0.0,0,1,0,0,0,0,0.0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,1,4,3,0,8,0,0,0,6,29,3,0,0,1,3,5,0,0,0,0,0,0,0,2,1,0

##Identify the year of birth for each player

In [13]:
#Calculate Year of Birth for DF1
from math import floor, ceil


df1['Born'] = 0

for i in range(len(df1)):
  print(df1.loc[i, 'Age'])
  age_str = str(df1.loc[i, 'Age']).split('-')
  age = float(age_str[0]) + (float(age_str[1]) / 365.0)
  age = round(age, 1)
  if ceil(age) - age <= 0.5:
    age = ceil(age)
  else:
    age = floor(age)
  born = 2023 - age
  df1.loc[i, 'Born'] = born

25-177
22-161
22-325
22-327
24-029
24-351
22-051
21-206
21-356
23-204
31-075
27-102
22-345
24-062
29-301
26-011
23-200
21-237
27-180
21-110
24-291
22-225
21-071
34-065
19-203
15-066
21-037
21-315
20-048
24-201
25-188
23-251
32-285
20-346
24-095
31-112
25-168
29-130
20-049
24-032
27-358
32-283
28-036
29-251
20-324
22-131
24-033
21-090
25-202
21-141
30-071
20-305
22-151
22-275
19-059
28-075
20-225
30-189
21-356
34-200
25-227
21-023
25-243
20-141
31-171
30-107
23-159
22-310
21-127
23-192
25-180
33-091
17-093
20-176
27-305
20-083
23-104
28-332
23-194
22-271
29-254
18-084
19-338
18-001
19-294
20-140
24-314
31-346
26-141
19-213
24-069
22-345
24-203
24-199
24-318
19-337
25-131
23-091
19-048
18-363
23-114
24-210
31-120
25-052
23-314
20-160
26-239
19-319
19-360
20-069
23-035
21-001
27-090
25-281
25-013
29-258
25-234
34-132
29-080
26-006
29-319
22-026
21-203
24-008
26-133
21-346
21-014
21-141
21-318
25-063
21-129
20-214
21-182
36-291
22-119
22-127
19-069
25-282
27-130
30-004
21-309
32-030
26-061
21-293
36-245
21-302
28-353
35-268
23-091
25-360
22-330
24-082
24-264
35-223
29-229
21-079
21-104
21-170
23-137
24-304
20-159
22-081
19-096
19-058
20-141
34-065
30-076
28-312
23-093
33-300
23-310
30-236
24-055
22-008
33-309
25-036
22-064
34-008
22-126
26-019
22-039
23-195
23-120
21-325
22-018
26-344
29-306
28-203
30-091
27-279
19-309
19-329
21-247
22-011
29-087
21-283
22-273
27-129
25-037
28-119
28-024
23-122
25-267
22-089
28-315
27-068
21-126
21-362
29-026
22-102
31-207
21-264
28-082
24-124
26-031
22-140
20-062
21-099
19-119
25-196
22-344
29-167
22-224
34-065
27-020
34-187
27-269
22-156
30-265
31-052
22-263
32-119
28-222
23-191
25-059
28-259
20-120
27-133
23-142
24-000
23-209
23-278
36-042
18-213
27-275
27-291
23-339
20-159
26-345
21-156
19-235
27-286
21-209
20-158
19-189
31-205
30-189
22-222
19-235
26-074
23-021
22-330
30-119
24-277
31-189
21-028
22-359
31-279
19-064
20-317
20-298
24-273
23-006
25-328
25-292
24-114
24-195
24-081
24-228
28-295
23-097
22-057
31-056
23-117
27-051
24-283
20-352
20-305
26-004
25-097
26-304
20-155
27-329
25-314
20-139
19-162
20-295
22-013
22-232
37-012
21-104
28-364
22-039
25-280
29-077
24-103
26-118
26-310
25-344
26-043
20-074
25-044
26-320
22-184
21-149
26-302
26-029
22-210
26-087
33-152
25-145
37-328
34-265
26-290
23-336
30-258
25-274
22-033
23-339
33-136
31-082
25-060
22-068
31-052
29-228
22-359
22-363
21-315
21-040
32-357
21-204
20-204
24-093
25-117
23-316
27-026
21-159
23-064
26-061
20-253
33-185
34-021
20-129
29-343
25-069
25-315
23-353
21-136
20-067
22-238
23-193
23-214
23-039
18-194
17-247
20-256
17-134
21-003
19-175
23-085
21-233
17-000
27-134
25-006
21-172
21-053
21-052
21-182
21-168
30-056
25-171
23-035
27-285
21-155
31-214
29-094
24-082
21-247
22-323
22-110
23-044
21-037
24-152
25-126
20-018
24-208
22-059
21-085
26-111
29-240
28-227
22-353
26-276
34-212
22-257
22-205
24-297
32-148
23-210
27-309
20-126
31-000
21-071
24-164
28-101
21-192
29-156
21-302
32-144
32-347
29-253
23-347
24-044
23-324
19-213
24-067
23-330
22-350
25-110
30-048
25-044
20-139
26-134
31-062
28-345
25-187
26-144
31-124
26-251
25-066
22-098
31-214
30-196
29-087
33-303
20-115
26-197
22-141
27-148
24-150
33-003
24-071
21-208
28-134
21-262
24-278
20-150
21-001
26-100
22-274
30-024
21-110
31-000
18-103
25-138
22-077
24-115
24-152
19-247
25-004
21-297
23-013
29-299
26-288
29-070
21-238
20-327
25-126
23-122
26-029
18-272
19-153
25-124
20-170
22-080
21-121
27-055

In [14]:
df1.head()

,Season,Squad,Comp,Player,Nation,Pos,Age,MP,Starts_Playing_Time,Min_Playing_Time,Mins_Per_90_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per_Minutes,Ast_Per_Minutes,G+A_Per_Minutes,G_minus_PK_Per_Minutes,G+A_minus_PK_Per_Minutes,xG_Per_Minutes,xAG_Per_Minutes,xG+xAG_Per_Minutes,npxG_Per_Minutes,npxG+xAG_Per_Minutes,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Born
0,2022-2023,Feyenoord,Eredivisie,Dávid Hancko,SVK,DF,25-177,31.0,31,2745,30.5,2,4,0,0,3.1,3.1,2.3,63,227,44,0.07,0.13,0.20,0.07,0.20,0.10,0.07,0.18,0.10,0.18,30.5,71,43,43,24,4,44,53,9,16,13,31,103,1,1986,2282,38119,13910,708,751,1056,1148,200,334,2.2,19,249,11,2,42,11,13.1,0,0,0,2282,2188,91,44,3,16,23,35,0,0,0,0,1986,3,13,65,52,2,2,6,3,0,6,3,0,0,3,0,0,2615,228,1015,1368,255,66,2615,19,13,5,1697,9450,6326,40,3,29,8,1818,12,19,2,23,0,0,0,231,37,24,1997
1,2022-2023,Feyenoord,Eredivisie,Orkun Kökçü,TUR,MF,22-161,32.0,31,2696,30.0,8,2,2,2,5.6,4.1,7.1,91,379,104,0.27,0.07,0.33,0.20,0.27,0.19,0.24,0.42,0.14,0.37,30.0,39,18,12,15,12,17,45,28,6,10,19,16,0,2044,2510,36150,12660,920,1008,845,979,219,393,8.1,89,327,75,18,82,29,25.5,21,2,2,2510,2252,249,106,11,15,149,32,108,50,16,0,2044,9,39,196,131,43,7,11,4,0,15,9,1,2,2,1,0,2839,42,356,1598,918,53,2837,60,30,22,1822,9357,4726,77,10,58,44,2057,23,27,0,149,0,0,0,241,9,11,2001
2,2022-2023,Feyenoord,Eredivisie,Lutsharel Geertruida,NED,"DF,MF",22-325,30.0,29,2572,28.6,3,2,0,0,3.2,3.2,2.4,64,211,48,0.10,0.07,0.17,0.10,0.17,0.11,0.08,0.20,0.11,0.20,28.6,48,34,24,21,3,21,28,7,6,6,31,48,1,1844,2043,32210,9930,746,802,948,1012,122,172,2.5,25,183,14,5,26,8,17.7,0,0,0,2043,1913,128,33,2,7,12,95,0,0,0,0,1844,2,16,66,60,2,1,1,2,0,7,6,0,1,0,0,0,2257,106,568,1380,321,33,2257,33,17,10,1516,8342,4900,40,5,22,15,1669,16,15,1,12,0,0,0,176,20,14,2000
3,2022-2023,Feyenoord,Eredivisie,Marcus Pedersen,NOR,DF,22-327,29.0,25,2117,23.5,1,2,0,0,1.5,1.5,2.3,114,54,141,0.04,0.09,0.13,0.04,0.13,0.07,0.10,0.16,0.07,0.16,23.5,41,23,20,14,7,24,28,4,4,12,9,60,1,966,1177,15285,2783,497,546,392,463,57,105,2.7,30,61,22,14,19,4,17.5,0,0,0,1177,997,178,9,0,5,61,169,0,0,0,0,966,2,32,59,52,0,5,1,0,1,5,4,0,1,0,0,0,1407,76,331,627,464,66,1407,60,32,22,811,6081,3366,58,21,27,18,839,27,9,3,61,0,0,0,124,3,6,2000
4,2022-2023,Feyenoord,Eredivisie,Sebastian Szymański,POL,"MF,FW",24-029,29.0,24,1966,21.8,9,4,0,0,6.0,6.0,4.1,39,91,142,0.41,0.18,0.60,0.41,0.60,0.27,0.19,0.46,0.27,0.46,21.8,51,29,13,26,12,24,47,23,2,26,11,11,1,582,829,9164,2961,310,363,179,249,61,128,5.4,50,48,36,11,59,23,19.4,4,0,0,829,704,121,15,4,7,115,5,87,42,19,0,582,4,33,107,62,32,4,3,3,3,12,9,1,0,1,1,0,1118,13,93,430,600,92,1118,49,14,31,613,2897,1414,32,9,47,27,704,25,33,1,115,0,0,0,96,7,27,1999

In [15]:
df1['Comp'] = 'Eredivisie'

##Set the 'Nation' variable value to 'Unknown' for players whose nations are missing

In [16]:
#Nation to Unknown

for i in range(len(df1)):
  if df1.loc[i, 'Nation'] == 0:
    df1.loc[i, 'Nation'] = 'Unknown'

##Create a Primary Key to uniquely identify each observation of DF1

In [17]:
df1['temp'] = df1['Player'].map(str) + df1['Squad'].map(str) + df1['Nation'].map(str)

In [18]:
len(df1)

487

In [19]:
df1['temp'].value_counts()

Dávid HanckoFeyenoordSVK                 1
Magnus MattssonNEC NijmegenDEN           1
Mats SeuntjensFortuna SittardNED         1
Rémy VitaFortuna SittardMAD              1
Kristijan BistrovićFortuna SittardCRO    1
                                        ..
Mohammed TahiriSparta RotterdamNED       1
Omar RekikSparta RotterdamTUN            1
Rick MeijssenSparta RotterdamNED         1
Pedro AlemañSparta RotterdamESP          1
Patrick JoostenGroningenNED              1
Name: temp, Length: 487, dtype: int64

In [20]:
len(set(df1['temp']))

487

In [21]:
list(df1.columns)

['Season',
 'Squad',
 'Comp',
 'Player',
 'Nation',
 'Pos',
 'Age',
 'MP',
 'Starts_Playing_Time',
 'Min_Playing_Time',
 'Mins_Per_90_Playing_Time',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'xG_Expected',
 'npxG_Expected',
 'xAG_Expected',
 'PrgC_Progression',
 'PrgP_Progression',
 'PrgR_Progression',
 'Gls_Per_Minutes',
 'Ast_Per_Minutes',
 'G+A_Per_Minutes',
 'G_minus_PK_Per_Minutes',
 'G+A_minus_PK_Per_Minutes',
 'xG_Per_Minutes',
 'xAG_Per_Minutes',
 'xG+xAG_Per_Minutes',
 'npxG_Per_Minutes',
 'npxG+xAG_Per_Minutes',
 'Mins_Per_90',
 'Tkl_Tackles',
 'TklW_Tackles',
 'Def 3rd_Tackles',
 'Mid 3rd_Tackles',
 'Att 3rd_Tackles',
 'Tkl_Challenges',
 'Att_Challenges',
 'Lost_Challenges',
 'Sh_Blocks',
 'Pass_Blocks',
 'Int',
 'Clr',
 'Err',
 'Cmp_Total',
 'Att_Total',
 'TotDist_Total',
 'PrgDist_Total',
 'Cmp_Short',
 'Att_Short',
 'Cmp_Medium',
 'Att_Medium',
 'Cmp_Long',
 'Att_Long',
 'xA',
 'KP',
 'Final_Third',
 'PPA',
 'CrsPA',
 'Sh_Standard',
 'SoT_Standard',
 'Dist_Standard',
 'FK_Standard',
 'PK_Standard',
 'PKatt_Standard',
 'Att',
 'Live_Pass_Types',
 'Dead_Pass_Types',
 'FK_Pass_Types',
 'TB_Pass_Types',
 'Sw_Pass_Types',
 'Crs_Pass_Types',
 'TI_Pass_Types',
 'CK_Pass_Types',
 'In_Corner_Kicks',
 'Out_Corner_Kicks',
 'Str_Corner_Kicks',
 'Cmp_Outcomes',
 'Off_Outcomes',
 'Blocks_Outcomes',
 'SCA_SCA',
 'PassLive_SCA_Types',
 'PassDead_SCA_Types',
 'TO_SCA_Types',
 'Sh_SCA_Types',
 'Fld_SCA_Types',
 'Def_SCA_Types',
 'GCA_GCA',
 'PassLive_GCA_Types',
 'PassDead_GCA_Types',
 'TO_GCA_Types',
 'Sh_GCA_Types',
 'Fld_GCA_Types',
 'Def_GCA_Types',
 'Touches_Touches',
 'Def Pen_Touches',
 'Def 3rd_Touches',
 'Mid 3rd_Touches',
 'Att 3rd_Touches',
 'Att Pen_Touches',
 'Live_Touches',
 'Att_Take_Ons',
 'Succ_Take_Ons',
 'Tkld_Take_Ons',
 'Carries_Carries',
 'TotDist_Carries',
 'PrgDist_Carries',
 'Final_Third_Carries',
 'CPA_Carries',
 'Mis_Carries',
 'Dis_Carries',
 'Rec_Receiving',
 'Fls',
 'Fld',
 'Off',
 'Crs',
 'PKwon',
 'PKcon',
 'OG',
 'Recov',
 'Won_Aerial_Duels',
 'Lost_Aerial_Duels',
 'Born',
 'temp']

##Calculated the number of years completed by each player in 2023

In [22]:
df1['Age'] = 2023 - df1['Born']
df1.head()

,Season,Squad,Comp,Player,Nation,Pos,Age,MP,Starts_Playing_Time,Min_Playing_Time,Mins_Per_90_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per_Minutes,Ast_Per_Minutes,G+A_Per_Minutes,G_minus_PK_Per_Minutes,G+A_minus_PK_Per_Minutes,xG_Per_Minutes,xAG_Per_Minutes,xG+xAG_Per_Minutes,npxG_Per_Minutes,npxG+xAG_Per_Minutes,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Born,temp
0,2022-2023,Feyenoord,Eredivisie,Dávid Hancko,SVK,DF,26,31.0,31,2745,30.5,2,4,0,0,3.1,3.1,2.3,63,227,44,0.07,0.13,0.20,0.07,0.20,0.10,0.07,0.18,0.10,0.18,30.5,71,43,43,24,4,44,53,9,16,13,31,103,1,1986,2282,38119,13910,708,751,1056,1148,200,334,2.2,19,249,11,2,42,11,13.1,0,0,0,2282,2188,91,44,3,16,23,35,0,0,0,0,1986,3,13,65,52,2,2,6,3,0,6,3,0,0,3,0,0,2615,228,1015,1368,255,66,2615,19,13,5,1697,9450,6326,40,3,29,8,1818,12,19,2,23,0,0,0,231,37,24,1997,Dávid HanckoFeyenoordSVK
1,2022-2023,Feyenoord,Eredivisie,Orkun Kökçü,TUR,MF,22,32.0,31,2696,30.0,8,2,2,2,5.6,4.1,7.1,91,379,104,0.27,0.07,0.33,0.20,0.27,0.19,0.24,0.42,0.14,0.37,30.0,39,18,12,15,12,17,45,28,6,10,19,16,0,2044,2510,36150,12660,920,1008,845,979,219,393,8.1,89,327,75,18,82,29,25.5,21,2,2,2510,2252,249,106,11,15,149,32,108,50,16,0,2044,9,39,196,131,43,7,11,4,0,15,9,1,2,2,1,0,2839,42,356,1598,918,53,2837,60,30,22,1822,9357,4726,77,10,58,44,2057,23,27,0,149,0,0,0,241,9,11,2001,Orkun KökçüFeyenoordTUR
2,2022-2023,Feyenoord,Eredivisie,Lutsharel Geertruida,NED,"DF,MF",23,30.0,29,2572,28.6,3,2,0,0,3.2,3.2,2.4,64,211,48,0.10,0.07,0.17,0.10,0.17,0.11,0.08,0.20,0.11,0.20,28.6,48,34,24,21,3,21,28,7,6,6,31,48,1,1844,2043,32210,9930,746,802,948,1012,122,172,2.5,25,183,14,5,26,8,17.7,0,0,0,2043,1913,128,33,2,7,12,95,0,0,0,0,1844,2,16,66,60,2,1,1,2,0,7,6,0,1,0,0,0,2257,106,568,1380,321,33,2257,33,17,10,1516,8342,4900,40,5,22,15,1669,16,15,1,12,0,0,0,176,20,14,2000,Lutsharel GeertruidaFeyenoordNED
3,2022-2023,Feyenoord,Eredivisie,Marcus Pedersen,NOR,DF,23,29.0,25,2117,23.5,1,2,0,0,1.5,1.5,2.3,114,54,141,0.04,0.09,0.13,0.04,0.13,0.07,0.10,0.16,0.07,0.16,23.5,41,23,20,14,7,24,28,4,4,12,9,60,1,966,1177,15285,2783,497,546,392,463,57,105,2.7,30,61,22,14,19,4,17.5,0,0,0,1177,997,178,9,0,5,61,169,0,0,0,0,966,2,32,59,52,0,5,1,0,1,5,4,0,1,0,0,0,1407,76,331,627,464,66,1407,60,32,22,811,6081,3366,58,21,27,18,839,27,9,3,61,0,0,0,124,3,6,2000,Marcus PedersenFeyenoordNOR
4,2022-2023,Feyenoord,Eredivisie,Sebastian Szymański,POL,"MF,FW",24,29.0,24,1966,21.8,9,4,0,0,6.0,6.0,4.1,39,91,142,0.41,0.18,0.60,0.41,0.60,0.27,0.19,0.46,0.27,0.46,21.8,51,29,13,26,12,24,47,23,2,26,11,11,1,582,829,9164,2961,310,363,179,249,61,128,5.4,50,48,36,11,59,23,19.4,4,0,0,829,704,121,15,4,7,115,5,87,42,19,0,582,4,33,107,62,32,4,3,3,3,12,9,1,0,1,1,0,1118,13,93,430,600,92,1118,49,14,31,613,2897,1414,32,9,47,27,704,25,33,1,115,0,0,0,96,7,27,1999,Sebastian SzymańskiFeyenoordPOL

##Create a Custom Primary Key to be used for Merging Transferred Players

In [23]:
df1['temp'] = df1['Player'].map(str) + df1['Nation'].map(str) + df1['Age'].map(str) + df1['Born'].map(str)
df1.head()

,Season,Squad,Comp,Player,Nation,Pos,Age,MP,Starts_Playing_Time,Min_Playing_Time,Mins_Per_90_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per_Minutes,Ast_Per_Minutes,G+A_Per_Minutes,G_minus_PK_Per_Minutes,G+A_minus_PK_Per_Minutes,xG_Per_Minutes,xAG_Per_Minutes,xG+xAG_Per_Minutes,npxG_Per_Minutes,npxG+xAG_Per_Minutes,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Born,temp
0,2022-2023,Feyenoord,Eredivisie,Dávid Hancko,SVK,DF,26,31.0,31,2745,30.5,2,4,0,0,3.1,3.1,2.3,63,227,44,0.07,0.13,0.20,0.07,0.20,0.10,0.07,0.18,0.10,0.18,30.5,71,43,43,24,4,44,53,9,16,13,31,103,1,1986,2282,38119,13910,708,751,1056,1148,200,334,2.2,19,249,11,2,42,11,13.1,0,0,0,2282,2188,91,44,3,16,23,35,0,0,0,0,1986,3,13,65,52,2,2,6,3,0,6,3,0,0,3,0,0,2615,228,1015,1368,255,66,2615,19,13,5,1697,9450,6326,40,3,29,8,1818,12,19,2,23,0,0,0,231,37,24,1997,Dávid HanckoSVK261997
1,2022-2023,Feyenoord,Eredivisie,Orkun Kökçü,TUR,MF,22,32.0,31,2696,30.0,8,2,2,2,5.6,4.1,7.1,91,379,104,0.27,0.07,0.33,0.20,0.27,0.19,0.24,0.42,0.14,0.37,30.0,39,18,12,15,12,17,45,28,6,10,19,16,0,2044,2510,36150,12660,920,1008,845,979,219,393,8.1,89,327,75,18,82,29,25.5,21,2,2,2510,2252,249,106,11,15,149,32,108,50,16,0,2044,9,39,196,131,43,7,11,4,0,15,9,1,2,2,1,0,2839,42,356,1598,918,53,2837,60,30,22,1822,9357,4726,77,10,58,44,2057,23,27,0,149,0,0,0,241,9,11,2001,Orkun KökçüTUR222001
2,2022-2023,Feyenoord,Eredivisie,Lutsharel Geertruida,NED,"DF,MF",23,30.0,29,2572,28.6,3,2,0,0,3.2,3.2,2.4,64,211,48,0.10,0.07,0.17,0.10,0.17,0.11,0.08,0.20,0.11,0.20,28.6,48,34,24,21,3,21,28,7,6,6,31,48,1,1844,2043,32210,9930,746,802,948,1012,122,172,2.5,25,183,14,5,26,8,17.7,0,0,0,2043,1913,128,33,2,7,12,95,0,0,0,0,1844,2,16,66,60,2,1,1,2,0,7,6,0,1,0,0,0,2257,106,568,1380,321,33,2257,33,17,10,1516,8342,4900,40,5,22,15,1669,16,15,1,12,0,0,0,176,20,14,2000,Lutsharel GeertruidaNED232000
3,2022-2023,Feyenoord,Eredivisie,Marcus Pedersen,NOR,DF,23,29.0,25,2117,23.5,1,2,0,0,1.5,1.5,2.3,114,54,141,0.04,0.09,0.13,0.04,0.13,0.07,0.10,0.16,0.07,0.16,23.5,41,23,20,14,7,24,28,4,4,12,9,60,1,966,1177,15285,2783,497,546,392,463,57,105,2.7,30,61,22,14,19,4,17.5,0,0,0,1177,997,178,9,0,5,61,169,0,0,0,0,966,2,32,59,52,0,5,1,0,1,5,4,0,1,0,0,0,1407,76,331,627,464,66,1407,60,32,22,811,6081,3366,58,21,27,18,839,27,9,3,61,0,0,0,124,3,6,2000,Marcus PedersenNOR232000
4,2022-2023,Feyenoord,Eredivisie,Sebastian Szymański,POL,"MF,FW",24,29.0,24,1966,21.8,9,4,0,0,6.0,6.0,4.1,39,91,142,0.41,0.18,0.60,0.41,0.60,0.27,0.19,0.46,0.27,0.46,21.8,51,29,13,26,12,24,47,23,2,26,11,11,1,582,829,9164,2961,310,363,179,249,61,128,5.4,50,48,36,11,59,23,19.4,4,0,0,829,704,121,15,4,7,115,5,87,42,19,0,582,4,33,107,62,32,4,3,3,3,12,9,1,0,1,1,0,1118,13,93,430,600,92,1118,49,14,31,613,2897,1414,32,9,47,27,704,25,33,1,115,0,0,0,96,7,27,1999,Sebastian SzymańskiPOL241999

##Ensure that the names and order of variables are consistent in Europe Top 5 Dataframe (where transferred players are merged) and this dataframe

In [24]:
top_5_cols = ['Season_End_Year', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Tkld_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial', '2023_flag', 'temp']

In [25]:
print(top_5_cols)

['Season_End_Year', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Tkld_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial', '2023_flag', 'temp']

In [26]:
print(list(df1.columns))

['Season', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts_Playing_Time', 'Min_Playing_Time', 'Mins_Per_90_Playing_Time', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Gls_Per_Minutes', 'Ast_Per_Minutes', 'G+A_Per_Minutes', 'G_minus_PK_Per_Minutes', 'G+A_minus_PK_Per_Minutes', 'xG_Per_Minutes', 'xAG_Per_Minutes', 'xG+xAG_Per_Minutes', 'npxG_Per_Minutes', 'npxG+xAG_Per_Minutes', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'PK_Standard', 'PKatt_Standard', 'Att', 'Live_Pass_Types', 'Dead_Pass_Types', 'FK_Pass_Types', 'TB_Pass_Types', 'Sw_Pass_Types', 'Crs_Pass_Types', 'TI_Pass_Types', 'CK_Pass_Types', 'In_Corner_Kicks', 'Out_Corner_Kicks', 'Str_Corner_Kicks', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA_Types', 'PassDead_SCA_Types', 'TO_SCA_Types', 'Sh_SCA_Types', 'Fld_SCA_Types', 'Def_SCA_Types', 'GCA_GCA', 'PassLive_GCA_Types', 'PassDead_GCA_Types', 'TO_GCA_Types', 'Sh_GCA_Types', 'Fld_GCA_Types', 'Def_GCA_Types', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take_Ons', 'Succ_Take_Ons', 'Tkld_Take_Ons', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial_Duels', 'Lost_Aerial_Duels', 'Born', 'temp']

In [27]:
df1 = df1[['Season', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP', 'Starts_Playing_Time', 'Min_Playing_Time',
       'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected',
       'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression',
       'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 
       'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard',
       'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass_Types', 'Dead_Pass_Types', 'FK_Pass_Types', 'TB_Pass_Types', 'Sw_Pass_Types', 'Crs_Pass_Types', 'TI_Pass_Types', 'CK_Pass_Types', 'In_Corner_Kicks', 'Out_Corner_Kicks',
       'Str_Corner_Kicks', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA_Types', 'PassDead_SCA_Types', 'TO_SCA_Types', 'Sh_SCA_Types', 'Fld_SCA_Types', 'Def_SCA_Types', 'GCA_GCA', 
       'PassLive_GCA_Types', 'PassDead_GCA_Types', 'TO_GCA_Types', 'Sh_GCA_Types', 'Fld_GCA_Types', 'Def_GCA_Types', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 
       'Live_Touches', 'Att_Take_Ons', 'Succ_Take_Ons', 'Tkld_Take_Ons', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 
       'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial_Duels', 'Lost_Aerial_Duels', 'temp']]

In [28]:
len(df1.columns)

112

In [29]:
df1.head()

,Season,Squad,Comp,Player,Nation,Pos,Age,Born,MP,Starts_Playing_Time,Min_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,temp
0,2022-2023,Feyenoord,Eredivisie,Dávid Hancko,SVK,DF,26,1997,31.0,31,2745,2,4,0,0,3.1,3.1,2.3,63,227,44,30.5,71,43,43,24,4,44,53,9,16,13,31,103,1,1986,2282,38119,13910,708,751,1056,1148,200,334,2.2,19,249,11,2,42,11,13.1,0,2282,2188,91,44,3,16,23,35,0,0,0,0,1986,3,13,65,52,2,2,6,3,0,6,3,0,0,3,0,0,2615,228,1015,1368,255,66,2615,19,13,5,1697,9450,6326,40,3,29,8,1818,12,19,2,23,0,0,0,231,37,24,Dávid HanckoSVK261997
1,2022-2023,Feyenoord,Eredivisie,Orkun Kökçü,TUR,MF,22,2001,32.0,31,2696,8,2,2,2,5.6,4.1,7.1,91,379,104,30.0,39,18,12,15,12,17,45,28,6,10,19,16,0,2044,2510,36150,12660,920,1008,845,979,219,393,8.1,89,327,75,18,82,29,25.5,21,2510,2252,249,106,11,15,149,32,108,50,16,0,2044,9,39,196,131,43,7,11,4,0,15,9,1,2,2,1,0,2839,42,356,1598,918,53,2837,60,30,22,1822,9357,4726,77,10,58,44,2057,23,27,0,149,0,0,0,241,9,11,Orkun KökçüTUR222001
2,2022-2023,Feyenoord,Eredivisie,Lutsharel Geertruida,NED,"DF,MF",23,2000,30.0,29,2572,3,2,0,0,3.2,3.2,2.4,64,211,48,28.6,48,34,24,21,3,21,28,7,6,6,31,48,1,1844,2043,32210,9930,746,802,948,1012,122,172,2.5,25,183,14,5,26,8,17.7,0,2043,1913,128,33,2,7,12,95,0,0,0,0,1844,2,16,66,60,2,1,1,2,0,7,6,0,1,0,0,0,2257,106,568,1380,321,33,2257,33,17,10,1516,8342,4900,40,5,22,15,1669,16,15,1,12,0,0,0,176,20,14,Lutsharel GeertruidaNED232000
3,2022-2023,Feyenoord,Eredivisie,Marcus Pedersen,NOR,DF,23,2000,29.0,25,2117,1,2,0,0,1.5,1.5,2.3,114,54,141,23.5,41,23,20,14,7,24,28,4,4,12,9,60,1,966,1177,15285,2783,497,546,392,463,57,105,2.7,30,61,22,14,19,4,17.5,0,1177,997,178,9,0,5,61,169,0,0,0,0,966,2,32,59,52,0,5,1,0,1,5,4,0,1,0,0,0,1407,76,331,627,464,66,1407,60,32,22,811,6081,3366,58,21,27,18,839,27,9,3,61,0,0,0,124,3,6,Marcus PedersenNOR232000
4,2022-2023,Feyenoord,Eredivisie,Sebastian Szymański,POL,"MF,FW",24,1999,29.0,24,1966,9,4,0,0,6.0,6.0,4.1,39,91,142,21.8,51,29,13,26,12,24,47,23,2,26,11,11,1,582,829,9164,2961,310,363,179,249,61,128,5.4,50,48,36,11,59,23,19.4,4,829,704,121,15,4,7,115,5,87,42,19,0,582,4,33,107,62,32,4,3,3,3,12,9,1,0,1,1,0,1118,13,93,430,600,92,1118,49,14,31,613,2897,1414,32,9,47,27,704,25,33,1,115,0,0,0,96,7,27,Sebastian SzymańskiPOL241999

In [30]:
cols = list(df1.columns)[8:-1]
cols

['MP',
 'Starts_Playing_Time',
 'Min_Playing_Time',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'xG_Expected',
 'npxG_Expected',
 'xAG_Expected',
 'PrgC_Progression',
 'PrgP_Progression',
 'PrgR_Progression',
 'Mins_Per_90',
 'Tkl_Tackles',
 'TklW_Tackles',
 'Def 3rd_Tackles',
 'Mid 3rd_Tackles',
 'Att 3rd_Tackles',
 'Tkl_Challenges',
 'Att_Challenges',
 'Lost_Challenges',
 'Sh_Blocks',
 'Pass_Blocks',
 'Int',
 'Clr',
 'Err',
 'Cmp_Total',
 'Att_Total',
 'TotDist_Total',
 'PrgDist_Total',
 'Cmp_Short',
 'Att_Short',
 'Cmp_Medium',
 'Att_Medium',
 'Cmp_Long',
 'Att_Long',
 'xA',
 'KP',
 'Final_Third',
 'PPA',
 'CrsPA',
 'Sh_Standard',
 'SoT_Standard',
 'Dist_Standard',
 'FK_Standard',
 'Att',
 'Live_Pass_Types',
 'Dead_Pass_Types',
 'FK_Pass_Types',
 'TB_Pass_Types',
 'Sw_Pass_Types',
 'Crs_Pass_Types',
 'TI_Pass_Types',
 'CK_Pass_Types',
 'In_Corner_Kicks',
 'Out_Corner_Kicks',
 'Str_Corner_Kicks',
 'Cmp_Outcomes',
 'Off_Outcomes',
 'Blocks_Outcomes',
 'SCA_SCA',
 'PassLive_SCA_Types',
 'PassDead_SCA_Types',
 'TO_SCA_Types',
 'Sh_SCA_Types',
 'Fld_SCA_Types',
 'Def_SCA_Types',
 'GCA_GCA',
 'PassLive_GCA_Types',
 'PassDead_GCA_Types',
 'TO_GCA_Types',
 'Sh_GCA_Types',
 'Fld_GCA_Types',
 'Def_GCA_Types',
 'Touches_Touches',
 'Def Pen_Touches',
 'Def 3rd_Touches',
 'Mid 3rd_Touches',
 'Att 3rd_Touches',
 'Att Pen_Touches',
 'Live_Touches',
 'Att_Take_Ons',
 'Succ_Take_Ons',
 'Tkld_Take_Ons',
 'Carries_Carries',
 'TotDist_Carries',
 'PrgDist_Carries',
 'Final_Third_Carries',
 'CPA_Carries',
 'Mis_Carries',
 'Dis_Carries',
 'Rec_Receiving',
 'Fls',
 'Fld',
 'Off',
 'Crs',
 'PKwon',
 'PKcon',
 'OG',
 'Recov',
 'Won_Aerial_Duels',
 'Lost_Aerial_Duels']

In [31]:
y = df1.copy()

In [32]:
len(cols)

103

##Now we Merge the Transferred Players

In [33]:
y = y.groupby(['temp', 'Player', 'Nation', 'Age', 'Born'])[cols].sum().reset_index()

In [34]:
y.head()

,temp,Player,Nation,Age,Born,MP,Starts_Playing_Time,Min_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels
0,Aaron MeijersNED361987,Aaron Meijers,NED,36,1987,13.0,1,294,0,0,0,0,0.0,0.0,0.3,9,12,18,3.3,12,7,4,5,3,9,19,10,0,2,4,8,0,179,233,3203,1226,84,91,78,96,16,35,0.3,4,13,3,2,1,1,22.0,0,233,186,47,7,0,0,15,40,0,0,0,0,179,0,7,8,7,1,0,0,0,0,1,1,0,0,0,0,0,268,13,87,110,72,2,268,6,2,1,142,810,342,7,0,1,2,151,4,7,0,15,0,0,0,32,6,4
1,Achraf DouiriNED241999,Achraf Douiri,NED,24,1999,9.0,5,382,0,0,0,0,0.1,0.1,0.0,7,9,6,4.2,22,12,8,9,5,12,19,7,4,6,5,8,0,121,167,2113,492,60,68,44,54,16,33,0.1,1,7,1,1,3,0,21.2,0,167,135,32,1,0,1,7,30,1,1,0,0,121,0,9,7,6,0,0,1,0,0,1,1,0,0,0,0,0,230,11,75,107,49,1,230,13,8,5,92,572,261,5,1,7,6,102,8,3,0,7,0,0,0,32,0,1
2,Adil AuassarNED371986,Adil Auassar,NED,37,1986,29.0,22,1918,0,0,0,0,0.2,0.2,0.3,9,73,1,21.3,34,23,27,7,0,15,25,10,26,4,34,112,2,1010,1182,21747,8443,287,310,560,608,155,237,1.3,3,67,3,0,4,2,13.9,0,1182,1114,64,25,2,12,2,1,0,0,0,0,1010,4,10,6,5,1,0,0,0,0,1,1,0,0,0,0,0,1428,275,815,601,21,12,1428,2,1,1,871,4664,2616,6,0,8,3,932,21,7,2,2,0,0,0,98,31,30
3,Adrian FeinGER241999,Adrian Fein,GER,24,1999,14.0,8,728,0,0,0,0,0.1,0.1,0.4,4,48,4,8.1,14,5,8,1,5,9,14,5,1,2,2,9,0,257,318,4253,1385,124,143,112,129,17,30,0.6,5,31,7,2,3,1,26.3,0,318,308,10,9,0,2,3,1,0,0,0,0,257,0,4,9,9,0,0,0,0,0,0,0,0,0,0,0,0,351,13,71,208,75,2,351,2,1,1,179,809,408,5,0,4,1,217,8,2,0,3,0,0,0,48,4,5
4,Ahmed El MessaoudiMAR281995,Ahmed El Messaoudi,MAR,28,1995,25.0,16,1408,2,0,0,0,2.6,2.6,0.8,34,58,52,15.6,23,14,9,10,4,5,19,14,6,17,9,16,0,485,598,6967,2006,280,326,154,179,22,37,1.3,16,44,12,3,27,10,16.3,0,598,588,9,7,5,4,8,0,0,0,0,0,485,1,21,38,26,1,6,2,2,1,2,2,0,0,0,0,0,792,28,145,411,254,36,792,54,30,18,508,3033,1452,28,2,41,31,573,15,29,2,8,0,0,0,72,28,21

##Identify the Position

In [35]:
#Find Position

for i in range(len(y)):
  t = y.loc[i, 'temp']

  df_t = df1.loc[df1['temp'] == t, ['Pos', 'Min_Playing_Time']].groupby(['Pos'])['Min_Playing_Time'].sum().reset_index()
  if len(df_t) > 1:
    print(df_t, i)
  pos = list(df_t['Pos'])
  mins = list(df_t['Min_Playing_Time'])
  max_mins_index = mins.index(max(mins))
  y.loc[i, 'Pos'] = pos[max_mins_index]

     Pos  Min_Playing_Time
0     DF               618
1  FW,MF                68 29
     Pos  Min_Playing_Time
0     FW                 7
1  MF,FW               198 65
     Pos  Min_Playing_Time
0     MF              2330
1  MF,DF                77 178
  Pos  Min_Playing_Time
0  DF                 6
1  MF              1069 250
     Pos  Min_Playing_Time
0     FW              1564
1  MF,FW               964 262
     Pos  Min_Playing_Time
0  FW,MF               528
1  MF,FW                33 301
     Pos  Min_Playing_Time
0     DF               143
1  DF,MF              1229 316
     Pos  Min_Playing_Time
0  FW,MF                17
1  MF,FW               396 321
     Pos  Min_Playing_Time
0     MF              1446
1  MF,FW               100 349
     Pos  Min_Playing_Time
0  FW,DF               127
1  FW,MF               372 432

In [36]:
y

,temp,Player,Nation,Age,Born,MP,Starts_Playing_Time,Min_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Pos
0,Aaron MeijersNED361987,Aaron Meijers,NED,36,1987,13.0,1,294,0,0,0,0,0.0,0.0,0.3,9,12,18,3.3,12,7,4,5,3,9,19,10,0,2,4,8,0,179,233,3203,1226,84,91,78,96,16,35,0.3,4,13,3,2,1,1,22.0,0,233,186,47,7,0,0,15,40,0,0,0,0,179,0,7,8,7,1,0,0,0,0,1,1,0,0,0,0,0,268,13,87,110,72,2,268,6,2,1,142,810,342,7,0,1,2,151,4,7,0,15,0,0,0,32,6,4,DF
1,Achraf DouiriNED241999,Achraf Douiri,NED,24,1999,9.0,5,382,0,0,0,0,0.1,0.1,0.0,7,9,6,4.2,22,12,8,9,5,12,19,7,4,6,5,8,0,121,167,2113,492,60,68,44,54,16,33,0.1,1,7,1,1,3,0,21.2,0,167,135,32,1,0,1,7,30,1,1,0,0,121,0,9,7,6,0,0,1,0,0,1,1,0,0,0,0,0,230,11,75,107,49,1,230,13,8,5,92,572,261,5,1,7,6,102,8,3,0,7,0,0,0,32,0,1,"DF,FW"
2,Adil AuassarNED371986,Adil Auassar,NED,37,1986,29.0,22,1918,0,0,0,0,0.2,0.2,0.3,9,73,1,21.3,34,23,27,7,0,15,25,10,26,4,34,112,2,1010,1182,21747,8443,287,310,560,608,155,237,1.3,3,67,3,0,4,2,13.9,0,1182,1114,64,25,2,12,2,1,0,0,0,0,1010,4,10,6,5,1,0,0,0,0,1,1,0,0,0,0,0,1428,275,815,601,21,12,1428,2,1,1,871,4664,2616,6,0,8,3,932,21,7,2,2,0,0,0,98,31,30,DF
3,Adrian FeinGER241999,Adrian Fein,GER,24,1999,14.0,8,728,0,0,0,0,0.1,0.1,0.4,4,48,4,8.1,14,5,8,1,5,9,14,5,1,2,2,9,0,257,318,4253,1385,124,143,112,129,17,30,0.6,5,31,7,2,3,1,26.3,0,318,308,10,9,0,2,3,1,0,0,0,0,257,0,4,9,9,0,0,0,0,0,0,0,0,0,0,0,0,351,13,71,208,75,2,351,2,1,1,179,809,408,5,0,4,1,217,8,2,0,3,0,0,0,48,4,5,MF
4,Ahmed El MessaoudiMAR281995,Ahmed El Messaoudi,MAR,28,1995,25.0,16,1408,2,0,0,0,2.6,2.6,0.8,34,58,52,15.6,23,14,9,10,4,5,19,14,6,17,9,16,0,485,598,6967,2006,280,326,154,179,22,37,1.3,16,44,12,3,27,10,16.3,0,598,588,9,7,5,4,8,0,0,0,0,0,485,1,21,38,26,1,6,2,2,1,2,2,0,0,0,0,0,792,28,145,411,254,36,792,54,30,18,508,3033,1452,28,2,41,31,573,15,29,2,8,0,0,0,72,28,21,"MF,FW"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,Zakaria BakkaliBEL271996,Zakaria Bakkali,BEL,27,1996,0.0,1,445,3,0,0,0,1.4,1.4,1.1,31,17,48,4.9,8,6,5,2,1,5,5,0,0,2,2,3,0,127,172,1996,544,68,80,43,53,10,19,1.3,8,5,10,3,15,4,19.2,0,172,157,15,1,1,0,19,6,7,3,1,0,127,0,5,14,9,3,0,2,0,0,0,0,0,0,0,0,0,252,8,30,79,150,24,252,34,15,15,158,1269,640,25,7,12,8,176,4,14,6,19,0,0,0,20,0,5,"FW,DF"
470,Zakaria LabyadMAR301993,Zakaria Labyad,MAR,30,1993,0.0,3,249,1,0,0,0,0.3,0.3,0.1,1,9,13,2.8,5,4,2,3,0,2,9,7,0,3,1,0,0,61,93,841,216,33,42,20,27,3,10,0.3,3,7,3,0,4,3,17.5,1,93,88,3,0,1,0,6,1,1,0,0,0,61,2,4,8,7,1,0,0,0,0,0,0,0,0,0,0,0,116,1,13,61,43,6,116,0,0,0,59,152,59,4,0,6,5,80,4,1,0,6,0,0,0,9,1,1,"FW,MF"
471,Zico BuurmeesterNED212002,Zico Buurmeester,NED,21,2002,0.0,0,62,1,0,0,0,0.2,0.2,0.0,0,2,1,0.7,0,0,0,0,0,0,1,1,0,2,0,3,0,34,41,473,210,17,19,13,14,1,4,0.0,0,5,0,0,1,1,15.9,0,41,39,2,0,0,0,0,2,0,0,0,0,34,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,54,2,17,22,15,3,54,3,0,3,36,83,15,1,0,1,1,37,3,1,0,0,0,0,0,8,2,2,MF
472,Zinho VanheusdenBEL241999,Zinho Vanheusden,BEL,24,1999,0.0,2,225,0,0,0,0,0.1,0.1,0.0,4,7,2,2.5,2,0,1,1,0,0,0,0,1,1,2,14,0,102,133,2042,546,29,36,58,70,15,24,0.0,0,6,0,0,3,1,18.6,0,133,128,4,4,0,1,1,0,0,0,0,0,102,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,158,19,82,69,7,2,158,0,0,0,99,561,285,1,0,0,0,100,3,2,0,1,0,1,0,18,9,11,DF
473,Úmaro EmbalóPOR222001,Úmaro Embaló,POR,22,2001,27.0,18,1470,3,3,0,0,1.6,1.6,2.1,45,26,126,16.3,34,23,14,15,5,13,24,11,0,15,8,11,0,247,384,3997,919,125,163,86,132,21,49,2.6,18,21,11,6,21,9,17.6,0,384,372,12,1,2,1,52,9,2,1,0,0,247,0,19,36,23,1,5,3,3,1,4,2,1,1,0,0,0,579,16,115,192,283,59,579,56,24,26,353,2431,1165,17,20,47,29,366,17,23,10,52,0,0,0,86,4,8,"FW,MF"

In [37]:
import warnings
warnings.filterwarnings("ignore")

In [38]:
set(y['Pos'])

{'DF', 'DF,FW', 'DF,MF', 'FW', 'FW,DF', 'FW,MF', 'MF', 'MF,DF', 'MF,FW'}

In [39]:
len(y)

474

##Identify the Squad. A player who as been transferred will have both squads listed under the 'Squad' variable

In [40]:
#Find Squad
for i in range(len(y)):
  t = y.loc[i, 'temp']

  df_t = df1.loc[df1['temp'] == t, ['Squad']]
  squad_list = list(df_t['Squad'])

  if len(squad_list) > 1:
    print(squad_list, i)

  s = ' + '.join(squad_list)

  y.loc[i, 'Squad'] = s

['Utrecht', 'Excelsior'] 29
['Feyenoord', 'Fortuna Sittard'] 65
['PSV Eindhoven', 'Go Ahead Eagles'] 133
['Feyenoord', 'Utrecht'] 178
['PSV Eindhoven', 'Vitesse'] 250
['RKC Waalwijk', 'Fortuna Sittard'] 262
['Emmen', 'Groningen'] 290
['Utrecht', 'Cambuur'] 301
['Feyenoord', 'Groningen'] 316
['Feyenoord', 'Excelsior'] 321
['AZ Alkmaar', 'Excelsior'] 349
['AZ Alkmaar', 'Sparta Rotterdam'] 417
['Vitesse', 'Fortuna Sittard'] 432

In [41]:
y

,temp,Player,Nation,Age,Born,MP,Starts_Playing_Time,Min_Playing_Time,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass_Types,Dead_Pass_Types,FK_Pass_Types,TB_Pass_Types,Sw_Pass_Types,Crs_Pass_Types,TI_Pass_Types,CK_Pass_Types,In_Corner_Kicks,Out_Corner_Kicks,Str_Corner_Kicks,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA_Types,PassDead_SCA_Types,TO_SCA_Types,Sh_SCA_Types,Fld_SCA_Types,Def_SCA_Types,GCA_GCA,PassLive_GCA_Types,PassDead_GCA_Types,TO_GCA_Types,Sh_GCA_Types,Fld_GCA_Types,Def_GCA_Types,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take_Ons,Succ_Take_Ons,Tkld_Take_Ons,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial_Duels,Lost_Aerial_Duels,Pos,Squad
0,Aaron MeijersNED361987,Aaron Meijers,NED,36,1987,13.0,1,294,0,0,0,0,0.0,0.0,0.3,9,12,18,3.3,12,7,4,5,3,9,19,10,0,2,4,8,0,179,233,3203,1226,84,91,78,96,16,35,0.3,4,13,3,2,1,1,22.0,0,233,186,47,7,0,0,15,40,0,0,0,0,179,0,7,8,7,1,0,0,0,0,1,1,0,0,0,0,0,268,13,87,110,72,2,268,6,2,1,142,810,342,7,0,1,2,151,4,7,0,15,0,0,0,32,6,4,DF,Sparta Rotterdam
1,Achraf DouiriNED241999,Achraf Douiri,NED,24,1999,9.0,5,382,0,0,0,0,0.1,0.1,0.0,7,9,6,4.2,22,12,8,9,5,12,19,7,4,6,5,8,0,121,167,2113,492,60,68,44,54,16,33,0.1,1,7,1,1,3,0,21.2,0,167,135,32,1,0,1,7,30,1,1,0,0,121,0,9,7,6,0,0,1,0,0,1,1,0,0,0,0,0,230,11,75,107,49,1,230,13,8,5,92,572,261,5,1,7,6,102,8,3,0,7,0,0,0,32,0,1,"DF,FW",Volendam
2,Adil AuassarNED371986,Adil Auassar,NED,37,1986,29.0,22,1918,0,0,0,0,0.2,0.2,0.3,9,73,1,21.3,34,23,27,7,0,15,25,10,26,4,34,112,2,1010,1182,21747,8443,287,310,560,608,155,237,1.3,3,67,3,0,4,2,13.9,0,1182,1114,64,25,2,12,2,1,0,0,0,0,1010,4,10,6,5,1,0,0,0,0,1,1,0,0,0,0,0,1428,275,815,601,21,12,1428,2,1,1,871,4664,2616,6,0,8,3,932,21,7,2,2,0,0,0,98,31,30,DF,Sparta Rotterdam
3,Adrian FeinGER241999,Adrian Fein,GER,24,1999,14.0,8,728,0,0,0,0,0.1,0.1,0.4,4,48,4,8.1,14,5,8,1,5,9,14,5,1,2,2,9,0,257,318,4253,1385,124,143,112,129,17,30,0.6,5,31,7,2,3,1,26.3,0,318,308,10,9,0,2,3,1,0,0,0,0,257,0,4,9,9,0,0,0,0,0,0,0,0,0,0,0,0,351,13,71,208,75,2,351,2,1,1,179,809,408,5,0,4,1,217,8,2,0,3,0,0,0,48,4,5,MF,Excelsior
4,Ahmed El MessaoudiMAR281995,Ahmed El Messaoudi,MAR,28,1995,25.0,16,1408,2,0,0,0,2.6,2.6,0.8,34,58,52,15.6,23,14,9,10,4,5,19,14,6,17,9,16,0,485,598,6967,2006,280,326,154,179,22,37,1.3,16,44,12,3,27,10,16.3,0,598,588,9,7,5,4,8,0,0,0,0,0,485,1,21,38,26,1,6,2,2,1,2,2,0,0,0,0,0,792,28,145,411,254,36,792,54,30,18,508,3033,1452,28,2,41,31,573,15,29,2,8,0,0,0,72,28,21,"MF,FW",Emmen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,Zakaria BakkaliBEL271996,Zakaria Bakkali,BEL,27,1996,0.0,1,445,3,0,0,0,1.4,1.4,1.1,31,17,48,4.9,8,6,5,2,1,5,5,0,0,2,2,3,0,127,172,1996,544,68,80,43,53,10,19,1.3,8,5,10,3,15,4,19.2,0,172,157,15,1,1,0,19,6,7,3,1,0,127,0,5,14,9,3,0,2,0,0,0,0,0,0,0,0,0,252,8,30,79,150,24,252,34,15,15,158,1269,640,25,7,12,8,176,4,14,6,19,0,0,0,20,0,5,"FW,DF",RKC Waalwijk
470,Zakaria LabyadMAR301993,Zakaria Labyad,MAR,30,1993,0.0,3,249,1,0,0,0,0.3,0.3,0.1,1,9,13,2.8,5,4,2,3,0,2,9,7,0,3,1,0,0,61,93,841,216,33,42,20,27,3,10,0.3,3,7,3,0,4,3,17.5,1,93,88,3,0,1,0,6,1,1,0,0,0,61,2,4,8,7,1,0,0,0,0,0,0,0,0,0,0,0,116,1,13,61,43,6,116,0,0,0,59,152,59,4,0,6,5,80,4,1,0,6,0,0,0,9,1,1,"FW,MF",Utrecht
471,Zico BuurmeesterNED212002,Zico Buurmeester,NED,21,2002,0.0,0,62,1,0,0,0,0.2,0.2,0.0,0,2,1,0.7,0,0,0,0,0,0,1,1,0,2,0,3,0,34,41,473,210,17,19,13,14,1,4,0.0,0,5,0,0,1,1,15.9,0,41,39,2,0,0,0,0,2,0,0,0,0,34,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,54,2,17,22,15,3,54,3,0,3,36,83,15,1,0,1,1,37,3,1,0,0,0,0,0,8,2,2,MF,AZ Alkmaar
472,Zinho VanheusdenBEL241999,Zinho Vanheusden,BEL,24,1999,0.0,2,225,0,0,0,0,0.1,0.1,0.0,4,7,2,2.5,2,0,1,1,0,0,0,0,1,1,2,14,0,102,133,2042,546,29,36,58,70,15,24,0.0,0,6,0,0,3,1,18.6,0,133,128,4,4,0,1,1,0,0,0,0,0,102,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,158,19,82,69,7,2,158,0,0,0,99,561,285,1,0,0,0,100,3,2,0,1,0,1,0,18,9,11,DF,AZ Alkmaar
473,Úmaro EmbalóPOR222001,Úmaro Embaló,POR,22,2001,27.0,18,1470,3,3,0,0,1.6,1.6,2.1,45,26,126,16.3,34,23,14,15,5,13,24,11,0,15,8,11,0,247,384,3997,919,125,163,86,132,21,49,2.6,18,21,11,6,21,9,17.6,0,384,372,12,1,2,1,52,9,2,1,0,0,247,0,19,36,23,1,5,3,3,1,4,2,1,1,0,0,0,579,16,115,192,283,59,579,56,24,26,353,2431,1165,17,20,47,29,366,17,23,10,52,0,0,0,86,4,8,"FW,MF",Fortuna Sittard

In [42]:
y.drop(columns = ['temp'], inplace = True)

##Upload the Europe Top 5 League Dataframe to ensure that column names match between present dataframe and Europe Top 5 Leagues

In [43]:
uploaded=files.upload()
df2=pd.read_csv(io.BytesIO(uploaded['Outfielders_Final_EuropeTop5.csv']))

Saving Outfielders_Final_EuropeTop5.csv to Outfielders_Final_EuropeTop5.csv

In [44]:
len(df2.columns)

109

In [45]:
len(y.columns)

109

In [46]:
X = y.copy()

In [47]:
top_5_cols = list(df2.columns)
y_cols = list(y.columns)
count = 0

for i in range(len(y_cols)):
  count += 1
  print(y_cols[i],top_5_cols[i], count)
  X.rename(columns = {y_cols[i]:top_5_cols[i]}, inplace = True)

Player Player 1
Nation Nation 2
Age Age 3
Born Born 4
MP MP_Playing 5
Starts_Playing_Time Starts_Playing 6
Min_Playing_Time Min_Playing 7
Gls Gls 8
Ast Ast 9
PK PK 10
PKatt PKatt 11
xG_Expected xG_Expected 12
npxG_Expected npxG_Expected 13
xAG_Expected xAG_Expected 14
PrgC_Progression PrgC_Progression 15
PrgP_Progression PrgP_Progression 16
PrgR_Progression PrgR_Progression 17
Mins_Per_90 Mins_Per_90 18
Tkl_Tackles Tkl_Tackles 19
TklW_Tackles TklW_Tackles 20
Def 3rd_Tackles Def 3rd_Tackles 21
Mid 3rd_Tackles Mid 3rd_Tackles 22
Att 3rd_Tackles Att 3rd_Tackles 23
Tkl_Challenges Tkl_Challenges 24
Att_Challenges Att_Challenges 25
Lost_Challenges Lost_Challenges 26
Sh_Blocks Sh_Blocks 27
Pass_Blocks Pass_Blocks 28
Int Int 29
Clr Clr 30
Err Err 31
Cmp_Total Cmp_Total 32
Att_Total Att_Total 33
TotDist_Total TotDist_Total 34
PrgDist_Total PrgDist_Total 35
Cmp_Short Cmp_Short 36
Att_Short Att_Short 37
Cmp_Medium Cmp_Medium 38
Att_Medium Att_Medium 39
Cmp_Long Cmp_Long 40
Att_Long Att_Long 41
xA xA 42
KP KP 43
Final_Third Final_Third 44
PPA PPA 45
CrsPA CrsPA 46
Sh_Standard Sh_Standard 47
SoT_Standard SoT_Standard 48
Dist_Standard Dist_Standard 49
FK_Standard FK_Standard 50
Att Att 51
Live_Pass_Types Live_Pass 52
Dead_Pass_Types Dead_Pass 53
FK_Pass_Types FK_Pass 54
TB_Pass_Types TB_Pass 55
Sw_Pass_Types Sw_Pass 56
Crs_Pass_Types Crs_Pass 57
TI_Pass_Types TI_Pass 58
CK_Pass_Types CK_Pass 59
In_Corner_Kicks In_Corner 60
Out_Corner_Kicks Out_Corner 61
Str_Corner_Kicks Str_Corner 62
Cmp_Outcomes Cmp_Outcomes 63
Off_Outcomes Off_Outcomes 64
Blocks_Outcomes Blocks_Outcomes 65
SCA_SCA SCA_SCA 66
PassLive_SCA_Types PassLive_SCA 67
PassDead_SCA_Types PassDead_SCA 68
TO_SCA_Types TO_SCA 69
Sh_SCA_Types Sh_SCA 70
Fld_SCA_Types Fld_SCA 71
Def_SCA_Types Def_SCA 72
GCA_GCA GCA_GCA 73
PassLive_GCA_Types PassLive_GCA 74
PassDead_GCA_Types PassDead_GCA 75
TO_GCA_Types TO_GCA 76
Sh_GCA_Types Sh_GCA 77
Fld_GCA_Types Fld_GCA 78
Def_GCA_Types Def_GCA 79
Touches_Touches Touches_Touches 80
Def Pen_Touches Def Pen_Touches 81
Def 3rd_Touches Def 3rd_Touches 82
Mid 3rd_Touches Mid 3rd_Touches 83
Att 3rd_Touches Att 3rd_Touches 84
Att Pen_Touches Att Pen_Touches 85
Live_Touches Live_Touches 86
Att_Take_Ons Att_Take 87
Succ_Take_Ons Succ_Take 88
Tkld_Take_Ons Tkld_Take 89
Carries_Carries Carries_Carries 90
TotDist_Carries TotDist_Carries 91
PrgDist_Carries PrgDist_Carries 92
Final_Third_Carries Final_Third_Carries 93
CPA_Carries CPA_Carries 94
Mis_Carries Mis_Carries 95
Dis_Carries Dis_Carries 96
Rec_Receiving Rec_Receiving 97
Fls Fls 98
Fld Fld 99
Off Off 100
Crs Crs 101
PKwon PKwon 102
PKcon PKcon 103
OG OG 104
Recov Recov 105
Won_Aerial_Duels Won_Aerial 106
Lost_Aerial_Duels Lost_Aerial 107
Pos Pos 108
Squad Squad 109

##Verify that no column has been missed out on renaming

In [48]:
len(X.columns.intersection(df2.columns))

109

In [49]:
X

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad
0,Aaron Meijers,NED,36,1987,13.0,1,294,0,0,0,0,0.0,0.0,0.3,9,12,18,3.3,12,7,4,5,3,9,19,10,0,2,4,8,0,179,233,3203,1226,84,91,78,96,16,35,0.3,4,13,3,2,1,1,22.0,0,233,186,47,7,0,0,15,40,0,0,0,0,179,0,7,8,7,1,0,0,0,0,1,1,0,0,0,0,0,268,13,87,110,72,2,268,6,2,1,142,810,342,7,0,1,2,151,4,7,0,15,0,0,0,32,6,4,DF,Sparta Rotterdam
1,Achraf Douiri,NED,24,1999,9.0,5,382,0,0,0,0,0.1,0.1,0.0,7,9,6,4.2,22,12,8,9,5,12,19,7,4,6,5,8,0,121,167,2113,492,60,68,44,54,16,33,0.1,1,7,1,1,3,0,21.2,0,167,135,32,1,0,1,7,30,1,1,0,0,121,0,9,7,6,0,0,1,0,0,1,1,0,0,0,0,0,230,11,75,107,49,1,230,13,8,5,92,572,261,5,1,7,6,102,8,3,0,7,0,0,0,32,0,1,"DF,FW",Volendam
2,Adil Auassar,NED,37,1986,29.0,22,1918,0,0,0,0,0.2,0.2,0.3,9,73,1,21.3,34,23,27,7,0,15,25,10,26,4,34,112,2,1010,1182,21747,8443,287,310,560,608,155,237,1.3,3,67,3,0,4,2,13.9,0,1182,1114,64,25,2,12,2,1,0,0,0,0,1010,4,10,6,5,1,0,0,0,0,1,1,0,0,0,0,0,1428,275,815,601,21,12,1428,2,1,1,871,4664,2616,6,0,8,3,932,21,7,2,2,0,0,0,98,31,30,DF,Sparta Rotterdam
3,Adrian Fein,GER,24,1999,14.0,8,728,0,0,0,0,0.1,0.1,0.4,4,48,4,8.1,14,5,8,1,5,9,14,5,1,2,2,9,0,257,318,4253,1385,124,143,112,129,17,30,0.6,5,31,7,2,3,1,26.3,0,318,308,10,9,0,2,3,1,0,0,0,0,257,0,4,9,9,0,0,0,0,0,0,0,0,0,0,0,0,351,13,71,208,75,2,351,2,1,1,179,809,408,5,0,4,1,217,8,2,0,3,0,0,0,48,4,5,MF,Excelsior
4,Ahmed El Messaoudi,MAR,28,1995,25.0,16,1408,2,0,0,0,2.6,2.6,0.8,34,58,52,15.6,23,14,9,10,4,5,19,14,6,17,9,16,0,485,598,6967,2006,280,326,154,179,22,37,1.3,16,44,12,3,27,10,16.3,0,598,588,9,7,5,4,8,0,0,0,0,0,485,1,21,38,26,1,6,2,2,1,2,2,0,0,0,0,0,792,28,145,411,254,36,792,54,30,18,508,3033,1452,28,2,41,31,573,15,29,2,8,0,0,0,72,28,21,"MF,FW",Emmen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,Zakaria Bakkali,BEL,27,1996,0.0,1,445,3,0,0,0,1.4,1.4,1.1,31,17,48,4.9,8,6,5,2,1,5,5,0,0,2,2,3,0,127,172,1996,544,68,80,43,53,10,19,1.3,8,5,10,3,15,4,19.2,0,172,157,15,1,1,0,19,6,7,3,1,0,127,0,5,14,9,3,0,2,0,0,0,0,0,0,0,0,0,252,8,30,79,150,24,252,34,15,15,158,1269,640,25,7,12,8,176,4,14,6,19,0,0,0,20,0,5,"FW,DF",RKC Waalwijk
470,Zakaria Labyad,MAR,30,1993,0.0,3,249,1,0,0,0,0.3,0.3,0.1,1,9,13,2.8,5,4,2,3,0,2,9,7,0,3,1,0,0,61,93,841,216,33,42,20,27,3,10,0.3,3,7,3,0,4,3,17.5,1,93,88,3,0,1,0,6,1,1,0,0,0,61,2,4,8,7,1,0,0,0,0,0,0,0,0,0,0,0,116,1,13,61,43,6,116,0,0,0,59,152,59,4,0,6,5,80,4,1,0,6,0,0,0,9,1,1,"FW,MF",Utrecht
471,Zico Buurmeester,NED,21,2002,0.0,0,62,1,0,0,0,0.2,0.2,0.0,0,2,1,0.7,0,0,0,0,0,0,1,1,0,2,0,3,0,34,41,473,210,17,19,13,14,1,4,0.0,0,5,0,0,1,1,15.9,0,41,39,2,0,0,0,0,2,0,0,0,0,34,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,54,2,17,22,15,3,54,3,0,3,36,83,15,1,0,1,1,37,3,1,0,0,0,0,0,8,2,2,MF,AZ Alkmaar
472,Zinho Vanheusden,BEL,24,1999,0.0,2,225,0,0,0,0,0.1,0.1,0.0,4,7,2,2.5,2,0,1,1,0,0,0,0,1,1,2,14,0,102,133,2042,546,29,36,58,70,15,24,0.0,0,6,0,0,3,1,18.6,0,133,128,4,4,0,1,1,0,0,0,0,0,102,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,158,19,82,69,7,2,158,0,0,0,99,561,285,1,0,0,0,100,3,2,0,1,0,1,0,18,9,11,DF,AZ Alkmaar
473,Úmaro Embaló,POR,22,2001,27.0,18,1470,3,3,0,0,1.6,1.6,2.1,45,26,126,16.3,34,23,14,15,5,13,24,11,0,15,8,11,0,247,384,3997,919,125,163,86,132,21,49,2.6,18,21,11,6,21,9,17.6,0,384,372,12,1,2,1,52,9,2,1,0,0,247,0,19,36,23,1,5,3,3,1,4,2,1,1,0,0,0,579,16,115,192,283,59,579,56,24,26,353,2431,1165,17,20,47,29,366,17,23,10,52,0,0,0,86,4,8,"FW,MF",Fortuna Sittard

In [50]:
X.to_csv('Outfielders_Eredivisie.csv', index = False)